version: "2.1"

volumes:
    bazel_cache:
    bazel_repository_cache:
    yarn_cache:

services:
    devserver:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./packages:/src
            - bazel_cache:/root/.cache/bazel/
            - bazel_repository_cache:/root/.cache/bazel_repository_cache/
            - yarn_cache:/usr/local/share/.cache/yarn/
        working_dir: /src
        command: ["/usr/local/bin/ibazel", "run", "//devserver", "--", "--port=3000"]
        # command: ["/bin/bash", "-c", "echo \"sleeping indefinitely\"; while true; do sleep 100; done"]
